name: Check golangci lint and publish docker images on main branch

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch internal/embed/bin/migra
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
  build-and-push-images:
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build migra
        run: ./build-migra.sh

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push trek Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/stack11/trek:latest
